services:
    orchestrator:
      build: ./orchestrator
      ports:
        - "80:4000"
      environment:
        password: ${password}
    app-service:
      build: ./services/app
      ports:
        - "4002:4002"
      environment:
        - DATABASE_URL: ${DATABASE_URL}
        - NODE_ENV: "production"
    user-service:
      build: ./services/users
      ports:
        - "4001:4001"
      environment:
        MONGO_CONNECTION: ${MONGO_CONNECTION}